{{- if .Values.timeplusAppserver.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: timeplus-appserver
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timeplus.labels" . | nindent 4 }}
    {{- if .Values.timeplusAppserver.labels }}
    {{- toYaml .Values.timeplusAppserver.labels | nindent 4 }}
    {{- end }}
spec:
  type: {{ .Values.timeplusAppserver.service.type }}
  {{- if .Values.timeplusAppserver.service.clusterIP }}
  clusterIP: {{ .Values.timeplusAppserver.service.clusterIP }}
  {{- end }}
  selector:
    {{- include "timeplus.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: timeplus-appserver
  ports:
  - name: http
    port: 8000
    protocol: TCP
    targetPort: 8000
    {{- if eq .Values.timeplusAppserver.service.type "NodePort" }}
    nodePort: {{ .Values.timeplusAppserver.service.nodePort }}
    {{- end }}
  - name: internal-http
    port: 8081
    protocol: TCP
    targetPort: 8081
{{- end }}