{{- if and .Values.timeplusAppserver.enabled .Values.timeplusAppserver.encryptionKey }}
apiVersion: v1
kind: Secret
metadata:
  name: timeplus-appserver-encryption-key
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timeplus.labels" . | nindent 4 }}
type: Opaque
stringData:
  NEUTRON_ENCRYPTION_KEY: {{ .Values.timeplusAppserver.encryptionKey | quote }}
{{- end }}
