{{- if .Values.timeplusd.enabled }}
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: timeplusd
  namespace: {{ .Release.Namespace | quote }}
  labels:
    {{- include "timeplus.labels" . | nindent 4 }}
    {{- if .Values.timeplusd.labels }}
    {{- toYaml .Values.timeplusd.labels | nindent 4 }}
    {{- end }}
spec:
  replicas: {{ .Values.timeplusd.replicas | default 3 }}
  serviceName: timeplusd-svc
  podManagementPolicy: Parallel
  persistentVolumeClaimRetentionPolicy:
    whenDeleted: {{ ternary "Delete" "Retain" .Values.global.pvcDeleteOnStsDelete }}
    whenScaled: {{ ternary "Delete" "Retain" .Values.global.pvcDeleteOnStsScale }}
  selector:
    matchLabels:
      {{- include "timeplus.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: timeplusd
  template:
    metadata:
      annotations:
        k8s.timeplus.io/config-sha: {{ include (print $.Template.BasePath "/timeplusd-ConfigMap.yaml") . | sha256sum }}
        k8s.timeplus.io/user-config-sha: {{ include (print $.Template.BasePath "/timeplusd-user-ConfigMap.yaml") . | sha256sum }}
        {{- if .Values.timeplusd.annotations }}
        {{- toYaml .Values.timeplusd.annotations | nindent 8 }}
        {{- end }}
      labels:
        {{- include "timeplus.podLabels" . | nindent 8 }}
        {{- if .Values.timeplusd.labels }}
        {{- toYaml .Values.timeplusd.labels | nindent 8 }}
        {{- end }}
        app.kubernetes.io/component: timeplusd
    spec:
      {{- dict "global" .Values.global "self" .Values.timeplusd | include "timeplus.nodeAssignment" | nindent 6 }}
      {{- if .Values.timeplusd.serviceAccountName }}
      serviceAccountName: {{ .Values.timeplusd.serviceAccountName }}
      {{- end }}
      initContainers:
      {{- with .Values.timeplusd.extraInitContainers }}
      {{- toYaml . | nindent 8 }}
      {{- end }}
        - name: timeplusd-init-job
          {{- if .Values.timeplusd.initJob.resources }}
          resources:
            {{- toYaml .Values.timeplusd.initJob.resources | nindent 12 }}
          {{- end }}
          image: {{ include "timeplus.fullImage" .Values.timeplusd.initJob }}
          {{- if .Values.timeplusd.initJob.imagePullPolicy }}
          imagePullPolicy: {{ .Values.timeplusd.initJob.imagePullPolicy }}
          {{- end }}
          {{ if .Values.timeplusd.enableCoreDump }}
          securityContext:
            privileged: true
          {{ end }}
          env:
            - name: NODENAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - "/bin/sh"
            - "-c"
            - |
              set -ex
              
              NODE_CONFIG=""
              {{- range $key, $value := .Values.timeplusd.locality }}
              if [[ "$NODENAME" == "{{ $key }}" ]]; then
                NODE_CONFIG="${NODE_CONFIG}  locality: {{ $value }}\n"
              fi
              {{- end }}
              
              {{- range $key, $value := .Values.timeplusd.advertisedHost }}
              if [[ "$HOSTNAME" == "{{ $key }}" ]]; then
                NODE_CONFIG="${NODE_CONFIG}  advertised_host: {{ $value }}\n"
              fi
              {{- end }}
              if [[ "$HOSTNAME" == "timeplusd-0" ]] || [[ "$HOSTNAME" == "timeplusd-1" ]] || [[ "$HOSTNAME" == "timeplusd-2" ]]; then
                echo "Metadata node\n"
              else
                ROLES='  roles:\n    "@replace": ""\n    role:\n      - Data\n'
                NODE_CONFIG="${NODE_CONFIG}${ROLES}"
                echo "$NODE_CONFIG"
              fi

              echo -e "node:\n${NODE_CONFIG}" >> /etc/timeplusd-server/config.d/z200-cluster-config.yaml

              {{ if .Values.timeplusd.enableCoreDump }}
              mkdir -p /var/lib/timeplusd/core_dump
              chmod a+w /var/lib/timeplusd/core_dump
              sysctl -w kernel.core_pattern=/var/lib/timeplusd/core_dump/core.%e.%p.%i.%t
              {{ end }}
          volumeMounts:
            - name: timeplusd-config-cluster
              mountPath: /etc/timeplusd-server/config.d
          {{ if .Values.timeplusd.enableCoreDump }}
            - name: timeplusd-history
              mountPath: /var/lib/timeplusd
          {{ end }}
      securityContext:
        fsGroup: 101
      {{- if .Values.timeplusd.securityContext }}
      {{- toYaml .Values.timeplusd.securityContext | nindent 8 }}
      {{- end }}
      {{- if .Values.global.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml .Values.global.imagePullSecrets | nindent 8 }}
      {{- end }}
      containers:
      - name: timeplusd
        image: {{ include "timeplus.fullImage" .Values.timeplusd }}
        {{- if .Values.timeplusd.imagePullPolicy }}
        imagePullPolicy: {{ .Values.timeplusd.imagePullPolicy }}
        {{- end }}
        command:
        {{- if .Values.timeplusd.sleep }}
          - "bash"
          - "-c"
          - "sleep 36000"
        {{- else }}
          - "/entrypoint.sh"
        {{- end }}
        ports:
          - name: http-streaming
            containerPort: 3218
            protocol: TCP
          - name: http-snapshot
            containerPort: 8123
            protocol: TCP
          - name: tcp-streaming
            containerPort: 8463
            protocol: TCP
          - name: tcp-internal
            containerPort: 8464
            protocol: TCP
          - name: tcp-snapshot
            containerPort: 7587
            protocol: TCP
          - name: metrics
            containerPort: 9363
            protocol: TCP
        {{- if .Values.timeplusd.resources }}
        resources:
          {{- toYaml .Values.timeplusd.resources | nindent 10 }}
        {{- end }}
        {{- if .Values.timeplusd.livenessProbe }}
        livenessProbe:
          {{- toYaml .Values.timeplusd.livenessProbe | nindent 10 }}
        {{- end }}
        env:
        - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        {{- if not .Values.timeplusd.advertisedHost }}
        - name: ADVERTISED_HOST
          value: "$(HOSTNAME).timeplusd-svc.{{ .Release.Namespace }}.svc.cluster.local"
        {{- end }}
        - name: METADATA_NODE_QUORUM
          value: {{ if .Values.timeplusd.metadataNodeQuorum }}{{ .Values.timeplusd.metadataNodeQuorum}}{{ else }}{{ include "timeplus.metadataNodeQuorum" . }}{{ end }}
        {{- if .Values.timeplusAppserver.enabledAIService }}
        - name: TIMEPLUS_HOST
          value: "localhost"
        - name: TIMEPLUS_USER
          value: {{ .Values.timeplusd.defaultAdminUsername | quote }}
        - name: TIMEPLUS_PASSWORD
          value: {{ .Values.timeplusd.defaultAdminPassword | quote }}
        {{- end }}
        {{- with .Values.timeplusd.extraEnvs }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        volumeMounts:
        - name: timeplusd-history
          mountPath: /var/lib/timeplusd
          subPath: {{ .Values.timeplusd.storage.history.subPath }}
        - name: timeplusd-stream
          mountPath: /var/lib/timeplusd/nativelog
          subPath: {{ .Values.timeplusd.storage.stream.nativelogSubPath }}
        - name: timeplusd-stream
          mountPath: /var/lib/timeplusd/metastore
          subPath: {{ .Values.timeplusd.storage.stream.metastoreSubPath }}
        {{- if .Values.timeplusd.storage.log.enabled }}
        - name: timeplusd-log
          mountPath: /var/log/timeplusd-server
          subPath: {{ .Values.timeplusd.storage.log.subPath }}
        {{- end }}
        - name: timeplusd-config
          mountPath: /etc/timeplusd-server/config.d/z100-default-config.yaml
          subPath: default-config.yaml
        - name: timeplusd-config-cluster
          mountPath: /etc/timeplusd-server/config.d/z200-cluster-config.yaml
          subPath: z200-cluster-config.yaml
        - name: timeplusd-config
          mountPath: /etc/timeplusd-server/config.d/z300-custom-config.yaml
          subPath: custom-config.yaml
        - name: timeplusd-user-config
          mountPath: /etc/timeplusd-server/users.d/z100-admin-user.yaml
          subPath: z100-admin-user.yaml
        - name: timeplusd-user-config
          mountPath: /etc/timeplusd-server/users.d/z200-extra-users.yaml
          subPath: z200-extra-users.yaml
        - name: timeplusd-user-config
          mountPath: /etc/timeplusd-server/users.yaml
          subPath: users.yaml
    {{- if .Values.prometheus_metrics.enabled }}
    {{- include "timeplus.vectorContainer" .Values.prometheus_metrics.vector | nindent 6 }}
    {{- end }}
    {{- with .Values.timeplusd.extraContainers }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
      volumes:
      - name: timeplusd-config-cluster
        emptyDir: {}
      - name: timeplusd-config
        configMap:
          name: timeplusd-config
          defaultMode: 0777
      - name: timeplusd-user-config
        configMap:
          name: timeplusd-user-config
          defaultMode: 0777
    {{- if .Values.prometheus_metrics.enabled }}
    {{- include "timeplus.vectorVolume" "timeplusd.toml" | nindent 6 }}
    {{- end }}
    {{- with .Values.timeplusd.extraVolumes }}
    {{- toYaml . | nindent 6 }}
    {{- end }}
  volumeClaimTemplates:
  {{- if .Values.timeplusd.storage.log.enabled }}
  - metadata:
      name: timeplusd-log
    spec:
      {{- with .Values.timeplusd.storage.log }}
      storageClassName: {{ .className }}
      accessModes:
      - {{ default .accessMode "ReadWriteOnce" }}
      volumeMode: Filesystem
      {{- if .selector }}
      selector:
        {{- toYaml .selector | nindent 8 }}
      {{- end }}
      resources:
        requests:
          storage: {{ .size }}
      {{- end }}
    {{- end }}
  - metadata:
      name: timeplusd-history
    spec:
      {{- with .Values.timeplusd.storage.history }}
      storageClassName: {{ .className }}
      accessModes:
      - {{ default .accessMode "ReadWriteOnce" }}
      volumeMode: Filesystem
      {{- if .selector }}
      selector:
        {{- toYaml .selector | nindent 8 }}
      {{- end }}
      resources:
        requests:
          storage: {{ .size }}
      {{- end }}
  - metadata:
      name: timeplusd-stream
    spec:
      {{- with .Values.timeplusd.storage.stream }}
      storageClassName: {{ .className }}
      accessModes:
      - {{ default .accessMode "ReadWriteOnce" }}
      volumeMode: Filesystem
      {{- if .selector }}
      selector:
        {{- toYaml .selector | nindent 8 }}
      {{- end }}
      resources:
        requests:
          storage: {{ .size }}
      {{- end }}
{{- end }}